pipeline:
  name: Build ikurtz-python-harness-cicd
  identifier: Build_bunrabbit_ikurtz_python_harness_cicd_1734299181803
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1734293510658
        repoName: bunrabbit/ikurtz-python-harness-cicd
        build: <+input>
