pipeline:
  name: Build ikurtz-python-harness-cicd
  identifier: Build_bunrabbit_ikurtz_python_harness_cicd_1734299181803
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Test and Push
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Unit Tests
                  identifier: Run_Unit_Tests
                  spec:
                    connectorRef: ikurtzdockerhub
                    image: python:3.10
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      pytest --junitxml=unit-tests.xml --tb=long || true
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - parallel:
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: Build and Push to Docker
                      identifier: Build_and_Push_to_Docker
                      spec:
                        connectorRef: ikurtzdockerhub
                        repo: kurtzy/ikurtz-harness-python
                        tags:
                          - <+pipeline.sequenceId>
                  - step:
                      type: BuildAndPushECR
                      name: Build and Push to ECR
                      identifier: Build_and_Push_to_ECR
                      spec:
                        connectorRef: ikurtzawsconnector
                        region: us-east-1
                        account: "957764302791"
                        imageName: v1
                        tags:
                          - <+pipeline.sequenceId>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ikurtzharnesscluster
              namespace: ikurtz-harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1734293510658
        repoName: bunrabbit/ikurtz-python-harness-cicd
        build: <+input>
