pipeline:
  name: Build ikurtz-python-harness-cicd
  identifier: Build_bunrabbit_ikurtz_python_harness_cicd_1734299181803
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build Test and Push
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Unit Tests
                  identifier: Run_Unit_Tests
                  spec:
                    connectorRef: ikurtzdockerhub
                    image: python:3.10
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      pytest --junitxml=unit-tests.xml --tb=long || true
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - step:
                  type: BuildAndPushECR
                  name: Build and Push to ECR
                  identifier: Build_and_Push_to_ECR
                  spec:
                    connectorRef: ikurtzawsconnector
                    region: us-east-1
                    account: "957764302791"
                    imageName: ikurtz-harness/python-cicd
                    tags:
                      - <+pipeline.sequenceId>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ikurtzharnesscluster
              namespace: ikurtz-harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
    - stage:
        name: Deploy to EKS
        identifier: Deploy_to_EKS
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: harnessguestbook
          environment:
            environmentRef: ikurtzdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ikurtz_k8s_infra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - ikurtz-harness-delegate-k8s
        when:
          pipelineStatus: Success
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1734293510658
        repoName: ikurtz-python-harness-cicd
        build: <+input>
