pipeline:
  name: Build ikurtz-python-harness-cicd
  identifier: Build_bunrabbit_ikurtz_python_harness_cicd_1734299181803
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_python_app
                  name: Build Python App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      python -m pip install --upgrade pip
                      pip install  pytest
                      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: ikurtzharnesscluster
              namespace: ikurtz-harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1734293510658
        repoName: bunrabbit/ikurtz-python-harness-cicd
        build: <+input>
